[package]
name = "netsblox-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.130", features = ["derive"] }
reqwest = {version = "0.11.9", features = ["json", "cookies"]}
futures-util = "0.3.19"
netsblox_core = { path = "../core", version = "0.1.0" }
tokio-tungstenite = {version = "0.16.1", features = ["native-tls"] }
tungstenite = "0.16.0"
tokio = "1.0.0"
derive_more = "0.99.17"
