[package]
name = "netsblox-api"
version = "1.6.0"
edition = "2021"
license = "MIT"
description = """
A client library for the NetsBlox cloud API
"""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.130", features = ["derive"] }
reqwest = {version = "0.11.20", features = ["json", "cookies"]}
futures-util = "0.3.19"
netsblox-api-common = { path = "../api-common", version = "1.6.0" }
tokio-tungstenite = {version = "0.20.0", features = ["native-tls"] }
tungstenite = "0.20.1"
tokio = "1.0.0"
derive_more = "0.99.17"
serde_json = "1.0.59"
bytes = "1.1"
wasm-bindgen = "0.2.92"
wasm-bindgen-futures = "0.4.42"
serde-wasm-bindgen = "0.6.5"
into-jsvalue-derive = "0.1.0"
gloo-net = "0.5.0"

# FIXME: this can be removed once a new release of wasm_bindgen is released.
# This is required for Vec<T> returns from the api
[patch.crates-io]
wasm-bindgen = { git = "https://github.com/rustwasm/wasm-bindgen", rev = "88efe46" }
