name: Run tests
on: [push]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: 5
      - name: Setup minio
        run: |
          docker run -d -p 9000:9000 --name minio -e "MINIO_ACCESS_KEY=KEY" -e "MINIO_SECRET_KEY=MYSECRET" minio/minio server /data
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test

  audit:
    name: audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cargo install cargo-audit
      - run: cargo generate-lockfile
      - run: cargo audit
